# Generated by Django 3.2.6 on 2021-09-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210910_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.SlugField(default='pidar', max_length=100, verbose_name='Url'),
        ),
    ]
