# Generated by Django 3.2.6 on 2021-09-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_category_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.AddField(
            model_name='companies',
            name='category',
            field=models.ManyToManyField(to='main.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.SlugField(default='', max_length=100, unique=True, verbose_name='Url'),
        ),
        migrations.AddField(
            model_name='companies',
            name='place',
            field=models.ManyToManyField(to='main.City'),
        ),
    ]
