# Generated by Django 3.2.6 on 2021-09-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210911_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='category',
            field=models.ManyToManyField(related_name='Категории', to='main.Category'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='place',
            field=models.ManyToManyField(related_name='Города', to='main.City'),
        ),
    ]
