# Generated by Django 3.2.6 on 2021-09-12 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_city_city_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Companies',
            new_name='Company',
        ),
    ]
