# Generated by Django 3.2.6 on 2021-09-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_companies_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='City_choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_choice', models.CharField(blank=True, choices=[('Омск', 'Омск'), ('Москва', 'Москва'), ('Санкт-Петербург', 'Санкт-Петербург'), ('Екатеринбург', 'Екатеринбург'), ('Сочи', 'Сочи')], max_length=50, null=True)),
            ],
        ),
    ]
