# Generated by Django 3.2.6 on 2021-09-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_city_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_choice',
            name='the_choice',
            field=models.CharField(blank=True, choices=[('b bc ', 'dfbf'), ('dthet', 'r'), ('rhg-rher', 'hthhjt'), ('aa', 'fsg'), ('hdth', 'tjt')], default='', max_length=50),
        ),
    ]
