# Generated by Django 3.2.6 on 2021-09-17 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_city_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
