# Generated by Django 3.2.6 on 2021-09-17 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_delete_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City_choice',
        ),
    ]
