# Generated by Django 3.2.6 on 2021-09-18 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_investicii_kommercheskie_tenderi_meri_podderjki_pervaya_socialnaya_birja_socialnie_projekti_tovari_d'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investicii',
            options={'verbose_name': 'Инвестиции', 'verbose_name_plural': 'Инвестиции'},
        ),
        migrations.AlterModelOptions(
            name='kommercheskie_tenderi',
            options={'verbose_name': 'Коммерческие тендеры', 'verbose_name_plural': 'Коммерческие тендеры'},
        ),
        migrations.AlterModelOptions(
            name='meri_podderjki',
            options={'verbose_name': 'Меры поддержки', 'verbose_name_plural': 'Меры поддержки'},
        ),
        migrations.AlterModelOptions(
            name='pervaya_socialnaya_birja',
            options={'verbose_name': 'Первая социальная биржа', 'verbose_name_plural': 'Первая социальная биржа'},
        ),
        migrations.AlterModelOptions(
            name='socialnie_projekti',
            options={'verbose_name': 'Социальные проекты', 'verbose_name_plural': 'Социальные проекты'},
        ),
        migrations.AlterModelOptions(
            name='tovari_dla_biznesa',
            options={'verbose_name': 'Товары для бизнеса', 'verbose_name_plural': 'Товары для бизнеса'},
        ),
        migrations.AlterModelOptions(
            name='uslugi_dla_biznesa',
            options={'verbose_name': 'Услуги для бизнеса', 'verbose_name_plural': 'Услуги для бизнеса'},
        ),
    ]
