# Generated by Django 3.2.6 on 2021-09-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210919_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.ManyToManyField(related_name='Категории', to='main.Uslugi_dla_biznesa'),
        ),
    ]
