# Generated by Django 3.2.6 on 2021-09-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_company_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='category',
        ),
        migrations.AddField(
            model_name='company',
            name='category_tovari_dla_biznesa',
            field=models.ManyToManyField(blank=True, related_name='Товары_для_бизнеса', to='main.Tovari_dla_biznesa'),
        ),
        migrations.AddField(
            model_name='company',
            name='category_uslugi_dla_biznesa',
            field=models.ManyToManyField(blank=True, related_name='Услуги_для_бизнеса', to='main.Uslugi_dla_biznesa'),
        ),
    ]
